//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_EMP_INFO: Table.IBase
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSexMan { get; set; }
    }
}
