//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.PlugIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Version_Server
    {
        public int ID { get; set; }
        public Int32 AppSource { get; set; }
        public Int32 Channel { get; set; }
        public Int32 VersionIndex { get; set; }

        public Int32 ServerLocation { get; set; }
    }
}
