//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugIn.Table
{
    using IKUS.LIB.TABLE;
    using System;
    using System.Collections.Generic;

    public partial class T_Push : IAdminCreateBase
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string FaceImage { get; set; }
        public string FaceVideo { get; set; }
        public string Link { get; set; }
        public Int32 AgreementType { get; set; }
        public string Describe { get; set; }
        public Nullable<System.DateTime> FirstDateTime { get; set; }
        public Nullable<System.DateTime> NextDateTime { get; set; }
        public Int32 PushTimes { get; set; }
        public Int32 RemainTimes { get; set; }
        public Int32 FrequencySeconds { get; set; }

        public Int32 CreateAdminID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Boolean? IsOpen { get; set; }

        public Int32 ShowCount { get; set; }
        public Int32 ClickCount { get; set; }
    }
}
